name: linuxtools
description: General Linux Tools for easier mangement of your system via a GUI
version: 0.0.0
repository: https://git.gay/Atmois/linuxtools

environment:
  sdk: ^3.5.3

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
